baseURL: "https://agrim.github.io/prtfoio/"
languageCode: en-us
title: Agrim Paneru
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # Theme settings
  DateFormat: "January 2, 2006"
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  ShowReadingTime: true
  mathjax: true
  customCSS: ["css/custom.css"]
  enableNextPrevLinks: true
  comments: true
  commento: true

  # SEO and site metadata
  title: "Agrim Paneru"
  description: "Agrim Paneru's portfolio and blog about machine learning, AI, and software engineering."
  og_title: "Agrim Paneru"
  og_description: "Explore Agrim Paneru's projects, blogs, and experience in the world of technology and machine learning."
  og_url: "https://agrim.github.io/prtfoio/"
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Agrim Paneru"
    subtitle: "Hi, I’m Agrim, a final-year Computer Engineering student at Pulchowk Campus, IOE. I have a strong passion for machine learning and enjoy exploring its diverse applications."
    imageWidth: 250
    imageHeight: 250
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1HIN6M2OoNCBzqWh7X6ytdg9dwSC361ki/view?usp=sharing"

  # Post settings
  hideDescriptionInList: false
  cover:
    hiddenInList: false
    hiddenInSingle: false

  # Social Icons
  socialIcons:
    - name: "email"
      url: "https://mail.google.com/mail/?view=cm&to=agrimpaneru00@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/agrim-paneru-6307a42a1/"
    - name: "github"
      url: "https://github.com/agrimpaneru"

  # Search configuration (Fuse.js)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Allow HTML in Markdown
markup:
  goldmark:
    renderer:
      unsafe: true
